
@HW001.Web_HostAddress = http://localhost:5250

//1) отримати користувачів
GET http://localhost:5250/api/users
Accept: application/json

###
//2) додати нового користувача
POST http://localhost:5250/api/users
Accept: application/json
Content-Type: application/json

{
  "Id": 4,
  "Name": "Andriy",
  "LastName": "Strelko",
  "Age": 48
}

###
//3) оновити дані користувача
PUT http://localhost:5250/api/users/1
Accept: application/json
Content-Type: application/json

{
  "Id": 1,
  "Name": "Artem",
  "LastName": "Strelko",
  "Age": 11
}

###
//4) видалити користувача
DELETE http://localhost:5250/api/users/4
Accept: application/json

### Додаткове задання ###

//Для оптимізації передачі великого обсягу даних
//(наприклад, мільйона користувачів) краще
//використовувати розбиття списку на частини
// щоб зменшити обсяг інформації,
//яка передається за один запит.

//Це дозволяє:
//- зменшити використання пам’яті
//- пришвидшити відповідь сервера
//- зменшити навантаження на мережу
//- знизити ймовірність помилок передачі даних при поганому інтернет-з’єднанні

//Також можна використовувати фільтрацію за полями
//(наприклад, ім’ям або віком користувача)
//та об’єкти представлення, щоб повертати
//лише потрібні дані, наприклад тільки прізвища користувачів.